version: "3.5"

services:
  yandex-tank:
    image: yandex/yandex-tank
    container_name: yandex-tank
    volumes:
      - .:/var/loadtest
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
